services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: compoundDB
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
    ports:
      - 3306:3306
  
  server:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./server/:/app
      - /app/node_modules
    environment:
      - PORT=8000

      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=compoundDB
    ports:
      - 8000:8000
    depends_on:
      mysql:
        condition: service_healthy
    command: sh -c "npm install && npm run dev:withDB"
